# Generated by Django 4.2.4 on 2023-08-10 13:02

from django.db import migrations, models


def set_status_true(apps, schema_editor):
    Employee = apps.get_model('api', 'Employee')
    Employee.objects.update(status=True)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_gear'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(set_status_true),
    ]
