# Generated by Django 4.2.4 on 2023-08-10 20:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_employee_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='GearLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField(default=5)),
                ('returned', models.BooleanField(default=False)),
                ('condition', models.TextField()),
                ('returned_condition', models.TextField()),
                ('checkout_date', models.TimeField(verbose_name=django.utils.timezone.now)),
                ('returned_date', models.TimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='api.company')),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device', to='api.gear')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to='api.employee')),
            ],
        ),
    ]
