# Generated by Django 4.2.4 on 2023-08-10 21:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_gearlog_checkout_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gearlog',
            name='checkout_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='gearlog',
            name='returned_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
